### ISSUE TITLE
Verify Transaction No Authorization Header was found

### ISSUE THREAD

**Issue by Ikxyz** [kehers/paystack#37]
When i try to validate a transaction from sever side it doesn't work,
I have set my header correctly and noting seem to work all i keep getting is `no authorization header found`
and please the documentation needs a little more work 
 Thanks
![image](https://user-images.githubusercontent.com/40415727/52978492-e08c8e00-33d1-11e9-9b8b-fac1670c3ecf.png)

**Comment by pryme0** [comment]
hello how did you solve this problem please

**Comment by Ikxyz** [comment]
@pryme0 i solved by passing the api key like this in my header

```
"Authorization": "Bearer sk-testxxxxxxxx"
```

Make sure there is only one space between  Bearer and you api key

**Comment by skynette** [comment]
Still doesnt work for me

**Comment by REALSTEVEIG** [comment]
I need help integrating payment into my ecommerce website with Nodejs. I cant figure out why I am still getting this error.

**Comment by pryme0** [comment]
> I need help integrating payment into my ecommerce website with Nodejs. I cant figure out why I am still getting this error.

@REALSTEVEIG  what have you tried ....paste a screenshot of your codebase for more clarity

**Comment by REALSTEVEIG** [comment]
![handlebarsR](https://user-images.githubusercontent.com/101066723/179040741-c48c548e-0f6e-42b2-96a4-aeebca901c0e.PNG)
![json](https://user-images.githubusercontent.com/101066723/179040760-bc95e928-9fc6-4649-aeee-5ad5db6bf535.PNG)
![paystack config](https://user-images.githubusercontent.com/101066723/179040768-45581747-9adc-4735-bd07-6a0b71d4469b.PNG)
![routes](https://user-images.githubusercontent.com/101066723/179040773-57567e90-089d-4ad6-96a4-79b858a282b4.PNG)

**Comment by REALSTEVEIG** [comment]
![controllers](https://user-images.githubusercontent.com/101066723/179041920-17bd3c38-48a8-4459-a56b-e4f83235eaf1.PNG)

**Comment by REALSTEVEIG** [comment]
@pryme0 Thank you for your prompt response.
So I am trying to implement payment on an ecommerce website with Nodejs, Express, MongoDB and Express handlebars (frontend).

I would like to fetch the product data from my database/product.json file. Then accept payments from which ever product the client selects on the frontend (GET). But I really don't know how to implement this procedure in the exports.Payment controller/route.

I hope the images I sent are not too messy. Please forgive me, I am a programming noob and this is actually my first time handling payments.
I also tried reading the documentation but it was not really helpful to me..

If I need to provide more information or clarification, please let me know. Thank you!!

**Comment by REALSTEVEIG** [comment]
![frontend](https://user-images.githubusercontent.com/101066723/179044554-4a2c9764-9e40-416c-b0d1-97f6d1b21d8f.PNG)

**Comment by REALSTEVEIG** [comment]
This is what the frontend looks like for perspective.

**Comment by REALSTEVEIG** [comment]
![WhatsApp Image 2022-07-14 at 6 27 59 PM (1)](https://user-images.githubusercontent.com/101066723/179046446-66c5d898-6b03-45a9-9e51-c4fe6917c2e4.jpeg)

This is what the frontend looks like for perspective.

**Comment by pryme0** [comment]
@REALSTEVEIG  are you adding bearer in to the header?

**Comment by REALSTEVEIG** [comment]
> @REALSTEVEIG  are you adding bearer in to the header?

**Comment by REALSTEVEIG** [comment]
> @REALSTEVEIG  are you adding bearer in to the header?

How do I do that sir?
Please is there a way I can connect with you on zoom?
I've been on this for over a week now..😟

**Comment by pryme0** [comment]
inside of the headers

"Authorization": "Bearer sk-testxxxxxxxx"

take a look at @Ikxyz  answer

you can schedule a call for 8pm  ..my email ..obochi2@gmail.com

**Comment by REALSTEVEIG** [comment]
> inside of the headers
> 
> "Authorization": "Bearer sk-testxxxxxxxx"
> 
> take a look at @Ikxyz  answer
> 
> you can schedule a call for 8pm  ..my email ..obochi2@gmail.com

Thank you sir..
I'll schedule a meeting for 8pm.

**Comment by REALSTEVEIG** [comment]
> inside of the headers
> 
> "Authorization": "Bearer sk-testxxxxxxxx"
> 
> take a look at @Ikxyz  answer
> 
> you can schedule a call for 8pm  ..my email ..obochi2@gmail.com

Good morning sir..

Please sir what time will you be free today since we missed yesterday's meeting?

Thank you 🙂

**Comment by Ikxyz** [comment]
Cool

**Comment by REALSTEVEIG** [comment]
> Cool

![bearer](https://user-images.githubusercontent.com/101066723/179370457-c236c7b3-2e17-4eab-a83a-8edf812bb205.PNG)

I still have not been able to fix the problem and I have added "Bearer" before the public key.

**Comment by Ikxyz** [comment]
Can you paste the response object

**Comment by REALSTEVEIG** [comment]
> Can you paste the response object 

I'm not sure what you mean by the response object.

**Comment by Ikxyz** [comment]
When you make the request the result of the request is what am asking for
